#!/usr/bin/env bash
#this script prints best school until the 4th and 8th iteration

dig=1
while(( dig<=10 )); do
if(( dig==4 )); then
echo "bad luck"
elif(( dig==8 )); then
echo "good luck"
else
echo "Best School"
fi
((dig++))
done
