#!/usr/bin/env bash
#this is a bash script that creates the given file and prints to infinity and beyond indefinetly, i hate teh kill command when a signal is received in teh SIGTERM 
# prints y u no love me when receiving a SiINT signal and finally deletes the file and terminates itsself


killme() {
rm /var/run/myscript.pid
exit 0
}

trap "echo 'I hate the kill command' && killme" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "killme" SIGQUIT
echo '$$' > /var/run/myscript.pid
while true
do
  echo "To infinity and beyond"
  sleep 2
done
